CONNECT US_TRACKVENTORY_PPI/1234

DROP TABLE DETALLE_COMPRAS;
DROP TABLE DETALLE_VENTAS;
DROP TABLE INVENTARIOS;
DROP TABLE VARIACION_PRODUCTOS;
DROP TABLE PERMISOS;
DROP TABLE PERFILES;
DROP TABLE COMPRAS;
DROP TABLE VENTAS;
DROP TABLE PRODUCTOS;
DROP TABLE USUARIOS;
DROP TABLE CATEGORIA_PRODUCTOS;
DROP TABLE TAMANOS;
DROP TABLE COLORES;
DROP TABLE FORMULARIOS;
DROP TABLE ROLES_;
DROP TABLE TIENDAS;

CREATE TABLE TIENDAS
(	ID_TIENDA	NUMBER(2),
	NOMBRE		VARCHAR2(50),
	DIRECCION	VARCHAR2(100));

CREATE TABLE ROLES_
(	ID_ROL		NUMBER(3),
	NOMBRE		VARCHAR2(100));

CREATE TABLE FORMULARIOS
(	ID_FORMULARIO	VARCHAR2(100),
	NOMBRE		VARCHAR2(100),
	DESCRIPCION	VARCHAR2(255));

CREATE TABLE COLORES
(	NOMBRE		VARCHAR2(50),
	HEX_COD		VARCHAR2(7));

CREATE TABLE TAMANOS
(	CODIGO		VARCHAR2(100),
	DESCRIPCION	VARCHAR2(255));

CREATE TABLE CATEGORIA_PRODUCTOS
(	ID_CATEGORIA_PRODUCTO NUMBER(4),
	NOMBRE		VARCHAR2(50),
	DESCRIPCION	VARCHAR2(255));

CREATE TABLE USUARIOS
(	ID_USUARIO	VARCHAR2(20),
	NOMBRE		VARCHAR2(50),
	P_APELLIDO	VARCHAR2(30),
	S_APELLIDO	VARCHAR2(30),
	TELEFONO	VARCHAR2(20),
	CORREO		VARCHAR2(50),
	CONTRASENA	VARCHAR2(255),
	USERNAME	VARCHAR2(50),
	ESTADO		NUMBER(1));

CREATE TABLE PRODUCTOS
(	REFERENCIA_PRODUCTO VARCHAR2(50),
	NOMBRE		VARCHAR2(100),
	PRECIO_COMPRA	NUMBER(12,2),
	PRECIO_VENTA	NUMBER(12,2),
	ID_CATEGORIA_PRODUCTO NUMBER(4));

CREATE TABLE VENTAS
(	ID_VENTA	VARCHAR2(50),
	ID_USUARIO	VARCHAR2(20),
	FECHA		DATE);

CREATE TABLE COMPRAS
(	ID_COMPRA	VARCHAR2(50),
	ID_USUARIO	VARCHAR2(20),
	FECHA		DATE);

CREATE TABLE INVENTARIOS
(	ID_INVENTARIO	VARCHAR2(50),
	ID_TIENDA	NUMBER(2),
	ID_VARIACION_PROD VARCHAR2(100),
	STOCK		NUMBER(4));

CREATE TABLE DETALLE_VENTAS
(	ID_DETALLE_VENTA NUMBER(4),
	ID_VENTA	VARCHAR2(50),
	ID_INVENTARIO	VARCHAR2(50),
	CANTIDAD	NUMBER(4),
	TOTAL		NUMBER(12,2));

CREATE TABLE DETALLE_COMPRAS
(	ID_DETALLE_COMPRA VARCHAR2(50),
	ID_COMPRA	VARCHAR2(50),
	ID_INVENTARIO	VARCHAR2(50),
	CANTIDAD	NUMBER(4),
	TOTAL		NUMBER(12,2));

CREATE TABLE PERFILES
(	ID_PERFIL	NUMBER(3),
	ID_ROL		NUMBER(3),
	ID_USUARIO	VARCHAR2(20));

CREATE TABLE PERMISOS
(	ID_PERFIL	NUMBER(3),
	ID_FORMULARIO	VARCHAR2(100));

CREATE TABLE VARIACION_PRODUCTOS
(	CODIGO_VARIACION_PRODUCTO VARCHAR2(100),
	ID_PRODUCTO	VARCHAR2(50),
	NOMBRE_COLOR	VARCHAR2(50),
	CODIGO_TAMANO	VARCHAR2(100));

PURGE TABLESPACE TS_TRACKVENTORY_PPI;