ALTER TABLE TIENDAS ADD CONSTRAINT PK_TIENDAS
	PRIMARY KEY (ID_TIENDA);
ALTER TABLE TIENDAS ADD CONSTRAINT NN_ID_TIENDA
	CHECK(ID_TIENDA IS NOT NULL);
ALTER TABLE TIENDAS ADD CONSTRAINT NN_NOMBRE_TIENDA
	CHECK(NOMBRE IS NOT NULL);


ALTER TABLE ROLES_ ADD CONSTRAINT PK_ROLES_
	PRIMARY KEY (ID_ROL);
ALTER TABLE ROLES_ ADD CONSTRAINT NN_ID_ROL
	CHECK(ID_ROL IS NOT NULL);
ALTER TABLE ROLES_ ADD CONSTRAINT NN_NOMBRE_ROL
	CHECK(NOMBRE IS NOT NULL);


ALTER TABLE FORMULARIOS ADD CONSTRAINT PK_FORMULARIOS
	PRIMARY KEY (ID_FORMULARIO);
ALTER TABLE FORMULARIOS ADD CONSTRAINT NN_ID_FORMULARIO
	CHECK(ID_FORMULARIO IS NOT NULL);
ALTER TABLE FORMULARIOS ADD CONSTRAINT NN_NOMBRE_FORMULARIO
	CHECK(NOMBRE IS NOT NULL);


ALTER TABLE COLORES ADD CONSTRAINT PK_COLORES
	PRIMARY KEY (NOMBRE);
ALTER TABLE COLORES ADD CONSTRAINT NN_NOMBRE_COLOR
	CHECK(NOMBRE IS NOT NULL);
ALTER TABLE COLORES ADD CONSTRAINT NN_HEX_CODE
	CHECK(HEX_COD IS NOT NULL);


ALTER TABLE TAMANOS ADD CONSTRAINT PK_TAMANOS
	PRIMARY KEY (CODIGO);
ALTER TABLE TAMANOS ADD CONSTRAINT NN_CODIGO
	CHECK(CODIGO IS NOT NULL);


ALTER TABLE CATEGORIA_PRODUCTOS ADD CONSTRAINT PK_CATEGORIA_PRODUCTOS
	PRIMARY KEY (ID_CATEGORIA_PRODUCTO);
ALTER TABLE CATEGORIA_PRODUCTOS ADD CONSTRAINT NN_ID_CATEGORIA_PRODUCTO
	CHECK(ID_CATEGORIA_PRODUCTO IS NOT NULL);
ALTER TABLE CATEGORIA_PRODUCTOS ADD CONSTRAINT NN_NOMBRE_CATEGORIA_PRODUCTO
	CHECK(NOMBRE IS NOT NULL);


ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS
	PRIMARY KEY (ID_USUARIO);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_ID_USUARIO
	CHECK(ID_USUARIO IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_NOMBRE_USUARIO
	CHECK(NOMBRE IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_P_APELLIDO_USUARIO
	CHECK(P_APELLIDO IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_S_APELLIDO_USUARIO
	CHECK(S_APELLIDO IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_TELEFONO_USUARIO
	CHECK(TELEFONO IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CORREO_USUARIO
	CHECK(CORREO IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_CONTRASENA_USUARIO
	CHECK(CONTRASENA IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_USERNAME_USUARIO
	CHECK(USERNAME IS NOT NULL);
ALTER TABLE USUARIOS ADD CONSTRAINT NN_ESTADO_USUARIO
	CHECK(ESTADO IS NOT NULL);


ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_REFERENCIA_PRODUCTO
	PRIMARY KEY(REFERENCIA_PRODUCTO);
ALTER TABLE PRODUCTOS ADD CONSTRAINT NN_REFERENCIA_PRODUCTO
	CHECK(REFERENCIA_PRODUCTO IS NOT NULL);
ALTER TABLE PRODUCTOS ADD CONSTRAINT NN_NOMBRE_PRODUCTO
	CHECK(NOMBRE IS NOT NULL);
ALTER TABLE PRODUCTOS ADD CONSTRAINT NN_PRECIO_COMPRA
	CHECK(PRECIO_COMPRA IS NOT NULL);
ALTER TABLE PRODUCTOS ADD CONSTRAINT NN_PRECIO_VENTA
	CHECK(PRECIO_VENTA IS NOT NULL);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_CATEGORIA_PRODUCTOS
	FOREIGN KEY (ID_CATEGORIA_PRODUCTO)
	REFERENCES CATEGORIA_PRODUCTOS (ID_CATEGORIA_PRODUCTO);


ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS
	PRIMARY KEY(ID_VENTA);
ALTER TABLE VENTAS ADD CONSTRAINT NN_FECHA_VENTA
	CHECK(FECHA IS NOT NULL);
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_USUARIOS
	FOREIGN KEY(ID_USUARIO)
	REFERENCES USUARIOS (ID_USUARIO);

ALTER TABLE COMPRAS ADD CONSTRAINT PK_COMPRAS
	PRIMARY KEY(ID_COMPRA);
ALTER TABLE COMPRAS ADD CONSTRAINT NN_FECHA_COMPRA
	CHECK(FECHA IS NOT NULL);
ALTER TABLE COMPRAS ADD CONSTRAINT FK_COMPRAS_USUARIOS
	FOREIGN KEY(ID_USUARIO)
	REFERENCES USUARIOS (ID_USUARIO);


ALTER TABLE PERFILES ADD CONSTRAINT PK_PERFILES
	PRIMARY KEY(ID_PERFIL);
ALTER TABLE PERFILES ADD CONSTRAINT NN_ID_PERFIL
	CHECK(ID_PERFIL IS NOT NULL);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_ROLES
	FOREIGN KEY(ID_ROL)
	REFERENCES ROLES_(ID_ROL);
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_USUARIOS
	FOREIGN KEY(ID_USUARIO)
	REFERENCES USUARIOS(ID_USUARIO);


ALTER TABLE PERMISOS ADD CONSTRAINT PK_PERMISOS
	PRIMARY KEY(ID_PERFIL, ID_FORMULARIO);
ALTER TABLE PERMISOS ADD CONSTRAINT FK_PERMISOS_PERFILES
	FOREIGN KEY(ID_PERFIL)
	REFERENCES PERFILES(ID_PERFIL);
ALTER TABLE PERMISOS ADD CONSTRAINT FK_PERMISOS_FORMULARIOS
	FOREIGN KEY(ID_FORMULARIO)
	REFERENCES FORMULARIOS(ID_FORMULARIO);


ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT PK_VARIACION_PRODUCTOS
	PRIMARY KEY(CODIGO_VARIACION_PRODUCTO);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT NN_CODIGO_VARIACION_PRODUCTO
	CHECK(CODIGO_VARIACION_PRODUCTO IS NOT NULL);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT NN_ID_PRODUCTO
	CHECK(ID_PRODUCTO IS NOT NULL);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT NN_CODIGO_TAMANO
	CHECK(CODIGO_TAMANO IS NOT NULL);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT FK_VARIACION_PRODUCTOS_PRODUCTOS
	FOREIGN KEY(ID_PRODUCTO)
	REFERENCES PRODUCTOS(REFERENCIA_PRODUCTO);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT FK_VARIACION_PRODUCTOS_COLORES
	FOREIGN KEY(NOMBRE_COLOR)
	REFERENCES COLORES(NOMBRE);
ALTER TABLE VARIACION_PRODUCTOS ADD CONSTRAINT FK_VARIACION_PRODUCTOS_TAMANOS
	FOREIGN KEY(CODIGO_TAMANO)
	REFERENCES TAMANOS(CODIGO);

ALTER TABLE INVENTARIOS ADD CONSTRAINT PK_INVENTARIOS
	PRIMARY KEY(ID_INVENTARIO);
ALTER TABLE INVENTARIOS ADD CONSTRAINT NN_ID_INVENTARIO
	CHECK(ID_INVENTARIO IS NOT NULL);
ALTER TABLE INVENTARIOS ADD CONSTRAINT NN_ID_VARIACION_PROD
	CHECK(ID_VARIACION_PROD IS NOT NULL);
ALTER TABLE INVENTARIOS ADD CONSTRAINT NN_STOCK
	CHECK(STOCK IS NOT NULL);
ALTER TABLE INVENTARIOS ADD CONSTRAINT FK_INVENTARIOS_TIENDAS
	FOREIGN KEY (ID_TIENDA)
	REFERENCES TIENDAS (ID_TIENDA);
ALTER TABLE INVENTARIOS ADD CONSTRAINT FK_INVENTARIOS_VARIACION_PRODUCTOS
	FOREIGN KEY (ID_VARIACION_PROD)
	REFERENCES VARIACION_PRODUCTOS(CODIGO_VARIACION_PRODUCTO);

ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT PK_DETALLE_VENTAS
	PRIMARY KEY (ID_DETALLE_VENTA);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT NN_ID_DETALLE_VENTA
	CHECK(ID_DETALLE_VENTA IS NOT NULL);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT NN_ID_VENTA
	CHECK(ID_VENTA IS NOT NULL);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT NN_CANTIDAD_VENTA
	CHECK(CANTIDAD IS NOT NULL);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT NN_TOTAL_VENTA
	CHECK(TOTAL IS NOT NULL);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT FK_DETALLE_VENTAS_VENTAS
	FOREIGN KEY(ID_VENTA)
	REFERENCES VENTAS(ID_VENTA);
ALTER TABLE DETALLE_VENTAS ADD CONSTRAINT FK_DETALLE_VENTAS_INVENTARIOS
	FOREIGN KEY(ID_INVENTARIO)
	REFERENCES INVENTARIOS (ID_INVENTARIO);


ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT PK_DETALLE_COMPRAS
	PRIMARY KEY (ID_DETALLE_COMPRA);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT NN_ID_DETALLE_COMPRA
	CHECK(ID_DETALLE_COMPRA IS NOT NULL);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT NN_ID_COMPRAS
	CHECK(ID_COMPRA IS NOT NULL);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT NN_CANTIDAD_COMPRA
	CHECK(CANTIDAD IS NOT NULL);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT NN_TOTAL_COMPRA
	CHECK(TOTAL IS NOT NULL);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT FK_DETALLE_COMPRAS_INVENTARIOS
	FOREIGN KEY(ID_COMPRA)
	REFERENCES COMPRAS(ID_COMPRA);
ALTER TABLE DETALLE_COMPRAS ADD CONSTRAINT FK_DETALLE_COMPRAS_COMPRAS
	FOREIGN KEY(ID_INVENTARIO)
	REFERENCES INVENTARIOS (ID_INVENTARIO);